[platformio]
default_envs = main_unit

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:main_unit]
board = adafruit_feather_esp32s3

build_src_filter =
    -<*>
    +<main_unit/**>
    +<navigation.cpp>
    +<nav_fusion.cpp>
    +<gps_sensor.cpp>
    +<imu_sensor.cpp> 
    +<motors.cpp>
    +<controller.cpp>
    +<anchor_controller.cpp>
    +<auto_controller.cpp>
    +<simulator.cpp>
    +<remote_espnow.cpp>
    +<buttons.cpp>
    +<input_logic.cpp>
    +<ota_update.cpp>
    
build_flags =
    
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    mikalhart/TinyGPSPlus
    adafruit/Adafruit BNO08x RVC

[env:remote_unit]
board = adafruit_feather_esp32s3

build_src_filter =
    -<*>
    +<remote_unit/**>
    +<display.cpp>
    +<display_status.cpp>
    +<imu_sensor.cpp> 
    +<ota_update.cpp>

build_flags =

    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    adafruit/Adafruit BNO08x RVC
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ILI9341

[env:remote2_unit]
board = esp32-s3-devkitc-1
build_src_filter =
    -<*>
    +<remote2_unit/**>
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ST7735 and ST7789 Library